apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: autocare-secrets
  namespace: autocare
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: autocare-secret-store
    kind: SecretStore
  target:
    name: autocare-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: autocare/jwt-secret
    - secretKey: DB_PASSWORD
      remoteRef:
        key: autocare/db-password
    - secretKey: DB_HOST
      remoteRef:
        key: autocare/rds-endpoint
