apiVersion: v1
kind: ServiceAccount
metadata:
  name: autocare-sa
  namespace: autocare
  annotations:
    # Must match Terraform output: terraform output -raw irsa_role_arn
    eks.amazonaws.com/role-arn: arn:aws:iam::673725943782:role/otasdp-poc-eks-ttsus-autocare-irsa
