apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ui-policy
  namespace: autocare
spec:
  podSelector:
    matchLabels:
      app: vehicle-maintenance-ui
  policyTypes:
    - Egress
  egress:
    # Allow egress to user-auth-service pods within the namespace
    - to:
        - podSelector:
            matchLabels:
              app: user-auth-service
      ports:
        - protocol: TCP
          port: 8080
    # Allow egress to vehicle-maintenance-service pods within the namespace
    - to:
        - podSelector:
            matchLabels:
              app: vehicle-maintenance-service
      ports:
        - protocol: TCP
          port: 8081
    # Allow DNS resolution
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
