apiVersion: v1
kind: Service
metadata:
  name: vehicle-maintenance-ui
  namespace: autocare
  labels:
    app: vehicle-maintenance-ui
spec:
  type: ClusterIP
  selector:
    app: vehicle-maintenance-ui
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
