apiVersion: v1
kind: Service
metadata:
  name: vehicle-maintenance-service
  namespace: autocare
  labels:
    app: vehicle-maintenance-service
spec:
  type: ClusterIP
  selector:
    app: vehicle-maintenance-service
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
